version: "3.4"


x-lang: &lang
  working_dir: &work_dir /atcoder
  volumes:
    - type: bind
      source: .
      target: *work_dir


services:

  ruby:
    <<: *lang
    image: ruby:2.3.3

  python:
    <<: *lang
    image: python:3.4.3

  rust:
    <<: *lang
    image: rust:1

  haskell:
    <<: *lang
    image: haskell:7.10.3

  js:
    <<: *lang
    image: node:5.12.0

  clj:
    <<: *lang
    image: clojure:openjdk-8-tools-deps
